site_name: LinkML for Fisheries Data Standardization
site_description: A demonstration of using LinkML to transform fisheries trawl survey data into Darwin Core Archives
site_author: Rutgers University Marine Field Station
site_url: https://sformel.github.io/IA_fisheries_trawl

repo_name: sformel/IA_fisheries_trawl
repo_url: https://github.com/sformel/IA_fisheries_trawl
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mermaid2:
      version: 10.6.1

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - Home: index.md
  - Workflow: workflow.md
  - Architecture:
    - Overview: architecture/overview.md
    - Data Models: architecture/data-models.md
    - Transformation Engine: architecture/transformation-engine.md
  - Schema Documentation:
    - Source Data Schema: schemas/source-data.md
    - Darwin Core Mappings: schemas/dwc-mappings.md
    - EML Mappings: schemas/eml-mappings.md
  - Outputs: outputs.md
  - Reusability Guide: reusability.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sformel/IA_fisheries_trawl
  generator: false

copyright: Copyright &copy; 2025 Rutgers University Marine Field Station